import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Vishnu's App",
  description: "Generated by create next app",
};

interface child {
  children: React.ReactNode;
}

const RootLayout = ({ children }: child) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
